# Generated by Django 4.2.9 on 2024-04-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'visitor'), (1, 'reader'), (2, 'administrator')], default=0),
        ),
    ]
