# Generated by Django 4.2.9 on 2024-04-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'reader'), (1, 'administrator')], default=0),
        ),
    ]
