# Generated by Django 4.2.9 on 2024-04-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abonement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='abonement_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='abonement_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
