# Generated by Django 4.2.9 on 2024-04-03 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_abonement_user_abonement_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='abonement',
        ),
        migrations.RemoveField(
            model_name='user',
            name='abonement_end',
        ),
        migrations.RemoveField(
            model_name='user',
            name='abonement_start',
        ),
        migrations.CreateModel(
            name='Abonement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abonement', models.BooleanField(default=False)),
                ('abonement_start', models.DateTimeField(blank=True, null=True)),
                ('abonement_end', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_of_days', models.PositiveIntegerField()),
                ('payment_status', models.IntegerField(choices=[(0, 'Вдало'), (1, 'Невдало')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
