# Generated by Django 4.2.9 on 2024-04-03 20:33

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files', validators=[books.validators.validate_is_pdf]),
        ),
    ]
