# Generated by Django 4.2.9 on 2024-04-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_is_being_read',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
