# Generated by Django 4.2.9 on 2024-04-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_book_is_being_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='book_is_being_read',
            new_name='is_being_read',
        ),
    ]
