# Generated by Django 4.2.9 on 2024-04-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_watchedlinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchedlinks',
            options={'verbose_name': 'WatchedLink', 'verbose_name_plural': 'WatchedLinks'},
        ),
        migrations.AlterModelTable(
            name='watchedlinks',
            table='watchedlink',
        ),
    ]
