# Generated by Django 4.2.9 on 2024-04-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='books',
            name='is_being_read',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
