# Generated by Django 4.2.9 on 2024-05-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_books_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='language',
            field=models.CharField(choices=[('англійська', 'англійська'), ('українська', 'українська')], default='українська', max_length=50),
        ),
    ]
