# Generated by Django 4.2.9 on 2024-04-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_status_order_order_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'В процесі обробки'), (1, 'Готово для отримання'), (2, 'Взято на читання'), (3, 'Протерміновано з отриманням'), (4, 'Протерміновано з поверненням'), (5, 'Повернуто')], default=0),
        ),
    ]
