# Generated by Django 4.2.9 on 2024-04-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Забронювати'), (1, 'Відмовитись')], default=0),
        ),
    ]
