# Generated by Django 4.2.9 on 2024-04-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'В процесі обробки'), (1, 'Готово для отримання'), (2, 'Взято на читання'), (3, 'Протерміновано з отриманням'), (4, 'Протерміновано з поверненням'), (5, 'Повернуто'), (6, 'Всі книги відмовлено')], default=0),
        ),
    ]
